FROM rocker/binder:latest

#.............................................................
# Adds binder abilities on top of the rocker/geospatial images
# see: https://hub.docker.com/r/rocker/binder
#.............................................................

LABEL maintainer='Lampros Mouselimis'

USER root

RUN sudo apt-get -y update && \
 sudo apt-get install unzip && \
 R -e "install.packages('devtools', dependencies = TRUE, repos = 'https://cloud.r-project.org/')" && \
 R -e "install.packages(c( 'glue', 'sf', 'lwgeom', 'units', 'data.table', 'httr', 'utils', 'foreach', 'tools', 'doParallel', 'magrittr', 'leaflet', 'leafgl', 'leaflet.extras', 'leafsync', 'miniUI', 'shiny', 'rnaturalearth', 'rmarkdown', 'knitr', 'lubridate', 'DT', 'mapview', 'grDevices', 'stargazer', 'reshape2', 'plotly', 'geodist', 'CopernicusDEM', 'terra', 'testthat', 'remotes' ), repos =  'https://cloud.r-project.org/' )"

RUN R -e "remotes::install_github('mlampros/IceSat2R', upgrade = 'always', dependencies = TRUE, repos = 'https://cloud.r-project.org/')" && \
 sudo apt-get autoremove -y && \
 sudo apt-get clean

ENV USER rstudio
