
#.............................................
# check every day if the "ATL03" is functional   [ once it becomes functional remove this cron-job ]
#.............................................

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: master

jobs:
 container:
   runs-on: ubuntu-latest
   timeout-minutes: 30
   container:
     image: mlampros/icesat2r:rstudiodev
     credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   steps:
     - name: Check Out Repo
       uses: actions/checkout@v3

     - name: Run the ATL03 httr-get
       working-directory: ${{ github.workspace }}
       run: |
          Rscript -e 'if (httr::GET(url = "https://openaltimetry.earthdatacloud.nasa.gov/data/api/icesat2/atl03?minx=140&miny=-6.641235&maxx=145&maxy=-1.641235&trackId=619&beamName=gt1l&outputFormat=csv&date=2021-02-02&client=portal&sampling=false")$status_code != 200) stop("ATL03 is not functional!")'
       shell: bash
