
#.....................................................
# check every day if the "ATL03" exists in the webpage
#.....................................................

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: master

jobs:
 container:
   runs-on: ubuntu-latest
   timeout-minutes: 30
   container:
     image: mlampros/icesat2r:rstudiodev
     credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   steps:
     - name: Check Out Repo
       uses: actions/checkout@v3

     - name: Run the ATL03 httr-get
       working-directory: ${{ github.workspace }}
       run: |
          Rscript -e "install.packages('rvest', repos = 'https://cloud.r-project.org/')"
          Rscript ATL03_temporary_1.R
       shell: bash
