
#........................................................................................................................
# build, push and cache the docker image, However don't cache the
# installation of the latest version of the IceSat2R package
# by adding the 'build-args' parameter
#
# References:
# https://docs.docker.com/ci-cd/github-actions/
# https://github.com/docker/build-push-action#customizing
# https://medium.com/@chamilad/lets-make-your-docker-image-better-than-90-of-existing-ones-8b1e5de950d
# https://stackoverflow.com/questions/35134713/disable-cache-for-specific-run-commands/49772666#comment108836586_49772666
# https://github.com/moby/moby/issues/1996#issuecomment-40334047
# https://github.com/moby/moby/issues/1996#issuecomment-51292997
#........................................................................................................................

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: docker_img

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          build-args: BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          file: ./Dockerfile_pkg
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/icesat2r:rstudiodev
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/icesat2r:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/icesat2r:buildcache,mode=max
