
#...................................................
# build, push and cache docker image
# see: https://docs.docker.com/ci-cd/github-actions/
#...................................................

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: docker_img

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile_pkg
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/icesat2r:rstudiodev
          #cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/icesat2r:buildcache
          #cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/icesat2r:buildcache,mode=max
